### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by dwhisman15** [viher3/ionic-gps-tracker#1]
No Map display?

**Comment by viher3** [comment]
Check this commit code: Line 27 to 71.

https://github.com/viher3/ionic-gps-tracker/blob/8dac7cdf5ccd14efa047af48839d893ab72c3f4f/www/js/app.js

And the view file is here: 

https://github.com/viher3/ionic-gps-tracker/blob/master/www/map.html

You have to replace your current "GpsController" with the old commit controller code.

Regards!

**Comment by dwhisman15** [comment]
Thanks, I tried it but still getting the same result. 
No Map displayed. 

Just print of coordinates

**Comment by viher3** [comment]
Add the "map.html" code into the "index.html" file. Or create a new route for this view.

**Comment by viher3** [comment]
@dwhisman15 can I modify this issue as solved?

**Comment by dwhisman15** [comment]
It is still not displaying map. I see the location center icon but no map is displaying

**Comment by viher3** [comment]
You have to check if Google Maps API script is loading correctly.
